version: '3.8'

services:
  backend:
    image: ${APP_NAME?APP_NAME is required}${ENV_SUFFIX}-backend:latest
    container_name: ${APP_NAME?APP_NAME is required}-backend
    hostname: ${APP_NAME?APP_NAME is required}-backend
    restart: unless-stopped
    build:
      context: ../
      dockerfile: deployment/docker/Dockerfile
      args:
        - ENV=${ENV}
        - SERVICE_NAME=backend
  

  consumer:
    image: ${APP_NAME?APP_NAME is required}${ENV_SUFFIX}-consumer:latest
    container_name: ${APP_NAME?APP_NAME is required}-consumer
    hostname: ${APP_NAME?APP_NAME is required}-consumer
    restart: unless-stopped
    build:
      context: ../
      dockerfile: deployment/docker/Dockerfile
      args:
        - ENV=${ENV}
        - SERVICE_NAME=consumer

  chat:
    image: ${APP_NAME?APP_NAME is required}${ENV_SUFFIX}-chat:latest
    container_name: ${APP_NAME?APP_NAME is required}-chat
    hostname: ${APP_NAME?APP_NAME is required}-chat
    restart: unless-stopped
    build:
      context: ../
      dockerfile: deployment/docker/Dockerfile
      args:
        - SERVICE_NAME=chat
        - ENV=${ENV}
    
  
networks:
  default:
    external: true
    name: $DEFAULT_NETWORK
