version: '3.9'
services:
  zookeeper-1:
    hostname: 'zookeeper-1'
    image: 'docker.io/library/zookeeper:3.6.3'
    init: true
    restart: always
    environment:
      ZOO_MY_ID: '1'
      ZOO_SERVERS: 'server.1=zookeeper-1:2888:3888'
      ZOO_CFG_EXTRA: 'clientPort=2181 peerPort=2888 leaderPort=3888'
      ZOO_INIT_LIMIT: '10'
      ZOO_SYNC_LIMIT: '5'
      ZOO_MAX_CLIENT_CNXNS: '0'
      ZOO_4LW_COMMANDS_WHITELIST: 'mntr,conf,ruok'
  kafka-1:
    hostname: 'kafka-1'
    image: 'sarama/fv-kafka-${KAFKA_VERSION:-3.6.0}'
    init: true
    build:
      context: .
      dockerfile: Dockerfile.kafka
      args:
        KAFKA_VERSION: ${KAFKA_VERSION:-3.6.0}
        SCALA_VERSION: ${SCALA_VERSION:-2.13}
    healthcheck:
      test:
        [
          'CMD',
          '/opt/kafka-${KAFKA_VERSION:-3.6.0}/bin/kafka-broker-api-versions.sh',
          '--bootstrap-server',
          'kafka-1:9091',
        ]
      interval: 15s
      timeout: 15s
      retries: 10
      start_period: 360s
    depends_on:
      - zookeeper-1
    restart: always
    environment:
      KAFKA_VERSION: ${KAFKA_VERSION:-3.6.0}
      KAFKA_CFG_ZOOKEEPER_CONNECT: 'zookeeper-1:2181'
      KAFKA_CFG_LISTENERS: 'LISTENER_INTERNAL://:9091,LISTENER_LOCAL://:29091'
      KAFKA_CFG_ADVERTISED_LISTENERS: 'LISTENER_INTERNAL://kafka-1:9091,LISTENER_LOCAL://localhost:29091'
      KAFKA_CFG_INTER_BROKER_LISTENER_NAME: 'LISTENER_INTERNAL'
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: 'LISTENER_INTERNAL:PLAINTEXT,LISTENER_LOCAL:PLAINTEXT'
      KAFKA_CFG_BROKER_ID: '1'
      KAFKA_CFG_BROKER_RACK: '1'
      KAFKA_CFG_ZOOKEEPER_SESSION_TIMEOUT_MS: '6000'
      KAFKA_CFG_ZOOKEEPER_CONNECTION_TIMEOUT_MS: '6000'
      KAFKA_CFG_DELETE_TOPIC_ENABLE: 'true'
      KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE: 'true'
      KAFKA_CFG_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_JVM_PERFORMANCE_OPTS: "-XX:+IgnoreUnrecognizedVMOptions"
    ports:
      - "29091:29091"
  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    depends_on:
      - kafka-1
      - zookeeper-1
    ports:
      - "8080:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka-1:9091
      KAFKA_CLUSTERS_0_ZOOKEEPER: zookeeper-1:2181
      KAFKA_CLUSTERS_0_PROPERTIES_SECURITY_PROTOCOL: PLAINTEXT