package errs

import "net/http"

var (
	ErrRoleInvalid                    = New(10000, "Role is invalid", http.StatusUnauthorized)
	ErrTokenInvalid                   = New(10001, "Token is invalid", http.StatusUnauthorized)
	ErrTokenExpired                   = New(10002, "Token is expired", http.StatusUnauthorized)
	ErrTokenMissing                   = New(10003, "Token is missing or malformed", http.StatusUnauthorized)
	ErrSessionTimeout                 = New(10004, "Session timeout", http.StatusUnauthorized)
	ErrPasswordExpiration             = New(10005, "Your current password was expired, please update new password.", http.StatusUnauthorized)
	ErrRequestTimeout                 = New(10006, "Your request is timeout, please try again", http.StatusInternalServerError)
	ErrGetTaskResultTimeout           = New(10007, "Get task result reached timeout", http.StatusInternalServerError)
	ErrRoleNotPermitted               = New(10008, "This side only available for Admin", http.StatusForbidden)
	ErrAccountInactive                = New(10009, "Your account is disabled, please contact support", http.StatusForbidden)
	ErrAccountExist                   = New(10010, "This account already exist", http.StatusBadRequest)
	ErrAccountStatusNotActive         = New(10011, "This account is not active", http.StatusForbidden)
	ErrRefreshTokenMissing            = New(10012, "Refresh Token is missing", http.StatusBadRequest)
	ErrAccountNotVerified             = New(10013, "This account is not verified", http.StatusForbidden)
	ErrAccountPendingReview           = New(10014, "This account is pending review", http.StatusForbidden)
	ErrExceedPermission               = New(10015, "Need permission to access this site", http.StatusForbidden)
	ErrAdminActionOnly                = New(10016, "Only admin can take this action", http.StatusForbidden)
	ErrClientActionOnly               = New(10017, "Only client can take this action", http.StatusForbidden)
	ErrInvalidActionBrandTeamMember   = New(10018, "Invalid brand team member action", http.StatusForbidden)
	ErrActionBrandTeamManagerOnly     = New(10019, "Only brand manager can take this action", http.StatusUnprocessableEntity)
	ErrTeamMemberAlreadyInAnotherTeam = New(10020, "Invite member already in another team", http.StatusUnprocessableEntity)
	ErrTeamMemberUserNotAbleToJoin    = New(10021, "The invited user is not able to join a team", http.StatusUnprocessableEntity)
	ErrInvalidBrandTeamManager        = New(10022, "Invite brand team manager", http.StatusUnprocessableEntity)
	ErrTeamMemberAlreadyInThisTeam    = New(10023, "Invite member already in this team", http.StatusUnprocessableEntity)
	ErrInvalidBrandTeam               = New(10024, "Invite brand team", http.StatusUnprocessableEntity)
	ErrCanNotInviteYourself           = New(10025, "Can not invite yourself", http.StatusUnprocessableEntity)
	ErrSignatureInvalid               = New(10026, "Token is invalid", http.StatusUnauthorized)
)

var (
	ErrValidation                     = New(20000, "Validation error", http.StatusUnprocessableEntity)
	ErrPasswordIncorrect              = New(20001, "Password is incorrect", http.StatusBadRequest)
	ErrPasswordRequired               = New(20002, "Password is required", http.StatusBadRequest)
	ErrPasswordInvalid                = New(20003, "Password is invalid", http.StatusBadRequest)
	ErrEmailTaken                     = New(20004, "There is already an account with this email address", http.StatusUnprocessableEntity)
	ErrEmailInvalid                   = New(20005, "Email is invalid", http.StatusUnprocessableEntity)
	ErrPhoneTaken                     = New(20006, "There is already an account with this phone number", http.StatusUnprocessableEntity)
	ErrPhoneInvalid                   = New(20007, "Phone number is invalid.", http.StatusUnprocessableEntity)
	ErrUserNotFound                   = New(20008, "User not found", http.StatusNotFound)
	ErrTokenResetPasswordInvalid      = New(20009, "Your reset password token is invalid or expired.", http.StatusBadRequest)
	ErrSocialTokenInvalid             = New(20010, "Social token is invalid", http.StatusBadRequest)
	ErrAvatarURLInvalid               = New(20011, "Avatar URL is invalid", http.StatusUnprocessableEntity)
	ErrBirthdayInvalid                = New(20012, "Birthday is invalid", http.StatusUnprocessableEntity)
	ErrEmailPhoneTaken                = New(20013, "Email & phone are already taken", http.StatusUnprocessableEntity)
	ErrEmailRequired                  = New(20014, "Email is required", http.StatusBadRequest)
	ErrPhoneRequired                  = New(20015, "Phone number is required.", http.StatusBadRequest)
	ErrLatRequired                    = New(20016, "Latitude is required", http.StatusBadRequest)
	ErrAccountTaken                   = New(20017, "An account with this email address already exists. Login or try with another email", http.StatusUnprocessableEntity)
	ErrLatInvalid                     = New(200176, "Latitude is invalid", http.StatusBadRequest)
	ErrLngRequired                    = New(20018, "Longitude is required", http.StatusBadRequest)
	ErrLngInvalid                     = New(200019, "Longitude is invalid", http.StatusBadRequest)
	ErrAddressRequired                = New(20020, "Address is required", http.StatusBadRequest)
	ErrTimezoneInvalid                = New(20021, "Timezone is invalid", http.StatusBadRequest)
	ErrTimezoneRequired               = New(20022, "Timezone is required", http.StatusBadRequest)
	ErrUserDeviceNotFound             = New(20023, "User's device not found", http.StatusNotFound)
	ErrAppVersionInvalid              = New(20024, "App version must be start with v (ex: v1.0.0)", http.StatusBadRequest)
	ErrUserIsAlreadyTaken             = New(20025, "Name already taken", http.StatusBadRequest)
	ErrPhoneOrEmailRequired           = New(20026, "Phone or email is required", http.StatusBadRequest)
	ErrInvalidOAuthLink               = New(20027, "Invalid Oauth, please try again", http.StatusBadRequest)
	ErrOldPasswordIncorrect           = New(20028, "Old password is incorrect", http.StatusBadRequest)
	ErrUserBankAccountNotFound        = New(20029, "User's bank account is not found", http.StatusNotFound)
	ErrOTPInvalid                     = New(20030, "Your OTP is invalid", http.StatusBadRequest)
	ErrOTPIncorrect                   = New(20031, "Your OTP is incorrect", http.StatusBadRequest)
	ErrPostalCodeRequired             = New(20032, "Postal code is required", http.StatusBadRequest)
	ErrPostalCodeInvalid              = New(20033, "Postal code is invalid format", http.StatusBadRequest)
	ErrCountryNotSupported            = New(20035, "Your country is not supported", http.StatusBadRequest)
	ErrPhoneOrEmailOrUserNameRequired = New(20036, "Phone or Email or Username is required", http.StatusBadRequest)
	ErrUserNameTaken                  = New(20037, "Username is taken", http.StatusBadRequest)
	ErrAuth0ClientNotFound            = New(20038, "Auth0's client is not found", http.StatusBadRequest)
	ErrAccountAlreadyVerified         = New(20039, "This account is already verified", http.StatusBadRequest)
	ErrLoginInvalid                   = New(20040, "Incorrect email and password", http.StatusBadRequest)
	ErrInvalidCheckoutLink            = New(20041, "Invalid checkout link", http.StatusBadRequest)
	ErrAddressNotFound                = New(20042, "Address is not found", http.StatusNotFound)
)

var (
	ErrProjectNotFound = New(30000, "Project is not found", http.StatusBadRequest)
)

var (
	ErrPreAuthCardFailed            = New(40000, "Please check with your bank to confirm this transaction was not flagged as fraud and try again later", http.StatusBadRequest)
	ErrPaymentRefunded              = New(40001, "Your payment was refunded", http.StatusBadRequest)
	ErrDefaultPaymentMethodNotFound = New(40002, "Your account has not have a default payment method", http.StatusBadRequest)
	ErrOrderCheckoutNotFound        = New(40003, "Payment does not exist", http.StatusBadRequest)
)

var (
	ErrPriceIDInvalid               = New(50000, "Price id is invalid", http.StatusBadRequest)
	ErrStripeCustomerIDInvalid      = New(50001, "Stripe customer id is invalid", http.StatusBadRequest)
	ErrStripePaymentIntentIDInvalid = New(50002, "Stripe payment intent id is invalid", http.StatusBadRequest)
	ErrStripePaymentMethodIDInvalid = New(50003, "Stripe payment method id is invalid", http.StatusBadRequest)
	ErrCardNotEnoughFunds           = New(5004, "Your card hasn't insufficient funds.", http.StatusBadRequest)
	ErrStripePaymentMethodNotAttach = New(50005, "The payment method didn't attach to this user", http.StatusBadRequest)
	ErrStripeBankAccountIDRequired  = New(50006, "Stripe bank account id is required", http.StatusBadRequest)
	ErrMinimumAmountRequired        = New(50007, "Your order must exceed .50 on the EZI-E app.", http.StatusBadRequest)
	ErrStripePaymentMissingName     = New(50008, "Your credit is missing name", http.StatusBadRequest)
	ErrCardDeclined                 = New(50009, "Your card is declined.", http.StatusBadRequest)
	ErrStripePaymentLinkIDInvalid   = New(50010, "Stripe payment link id is invalid", http.StatusBadRequest)
)

var (
	ErrCategoryNotFound       = New(60000, "Category not found", http.StatusNotFound)
	ErrCategoryExisted        = New(60001, "Category is already Existed", http.StatusBadRequest)
	ErrCategoryTaken          = New(60002, "Category is already taken", http.StatusBadRequest)
	ErrCategoryChildExisted   = New(60003, "Category child is existed", http.StatusBadRequest)
	ErrParentCategoryNotFound = New(60005, "Parent category not found", http.StatusBadRequest)
	ErrInvalidParentCategory  = New(60006, "Invalid parent category", http.StatusBadRequest)
)

var (
	ErrShopNotFound        = New(70000, "Shop not found", http.StatusNotFound)
	ErrShopExisted         = New(70001, "Shop is already Existed", http.StatusBadRequest)
	ErrShopAlreadyFollowed = New(70002, "Shop is already followed", http.StatusBadRequest)
)

var (
	ErrProductNotFound = New(80000, "Product not found", http.StatusNotFound)
	ErrProductExisted  = New(80001, "Product is already Existed", http.StatusBadRequest)
	ErrVariantNotFound = New(80002, "Variant  not found", http.StatusNotFound)
)

var (
	ErrRecordNotFound = New(90000, "Record is not found", http.StatusNotFound)
)

var (
	ErrChatRoomNotFound    = New(100000, "Chat Room is not found", http.StatusBadRequest)
	ErrChatRoomExisted     = New(100001, "Chat Room is already existed", http.StatusBadRequest)
	ErrChatRoomUserExisted = New(100001, "Chat Room User is already existed", http.StatusBadRequest)
)

var (
	ErrInquiryBuyerExisted                        = New(200000, "Already sent to buyer", http.StatusBadRequest)
	ErrInquiryOrderExisted                        = New(200001, "Inquiry order is already Existed", http.StatusBadRequest)
	ErrInquirySkuQuotationNotSent                 = New(200002, "Inquiry sku quotation is not sent", http.StatusBadRequest)
	ErrInquiryNotFound                            = New(200003, "Inquiry is not found", http.StatusNotFound)
	ErrInquiryCollectionTaken                     = New(200004, "Collection already exists", http.StatusUnprocessableEntity)
	ErrInquiryPurchaseOrderNotRemove              = New(200005, "Inquery is not able to remove", http.StatusUnprocessableEntity)
	ErrInquirySampleOrderIsNotPaid                = New(200006, "Sample order is not paid", http.StatusUnprocessableEntity)
	ErrInquiryInvalidToApproveQuotation           = New(200007, "Inquiry is invalid to approve quotation", http.StatusUnprocessableEntity)
	ErrInquiryInvalidToRejectQuotation            = New(200008, "Inquiry is invalid to reject quotation", http.StatusUnprocessableEntity)
	ErrInquiryInvalidToSendQuotationToBuyer       = New(200009, "Inquiry is invalid to send quotation to buyer", http.StatusUnprocessableEntity)
	ErrPoInvalidToCreateBulkOrder                 = New(200010, "Inquiry is in invalid to create bulk order", http.StatusUnprocessableEntity)
	ErrCanArchiveOnNewInquiryOnly                 = New(200011, "Can archive on new inquiry only", http.StatusUnprocessableEntity)
	ErrInquirySellerInvalidToApprove              = New(200012, "Inquiry seller quotation is invalid to approve", http.StatusUnprocessableEntity)
	ErrInquirySellerInvalidToReject               = New(200013, "Inquiry seller quotation is invalid to reject", http.StatusUnprocessableEntity)
	ErrSellerInvalidToPayout                      = New(200014, "Seller is invalid to payout, please check the PO details again", http.StatusUnprocessableEntity)
	ErrInquiryCartInvalidToCheckout               = New(200015, "Inquiry Cart has invalid checkout session. Please select item again.", http.StatusUnprocessableEntity)
	ErrInquiryEditTimeout                         = New(200016, "Inquiry edit session timeout", http.StatusUnprocessableEntity)
	ErrInquiryCartItemNotFound                    = New(200017, "Inquiry cart item is not found", http.StatusNotFound)
	ErrInquirySampleOrderIsNotConfirm             = New(200018, "Sample order is not able to confirm", http.StatusUnprocessableEntity)
	ErrInquirySellerNotFound                      = New(200013, "Inquiry seller is not found", http.StatusUnprocessableEntity)
	ErrInquirySellerInvalidToSendQuotationToBuyer = New(200014, "Inquiry seller is invalid to send quotation to admin", http.StatusUnprocessableEntity)
	ErrInquiryInvalidToCreatePaymentLink          = New(200015, "Inquiry is invalid to create payment link", http.StatusUnprocessableEntity)
)

var (
	ErrOrderCardSkuRequired = New(300000, "Inquiry sku is required", http.StatusBadRequest)

	ErrPoInvalidToApproveDesign      = New(300001, "Purchase order is invalid to approve design", http.StatusUnprocessableEntity)
	ErrPoInvalidToRejectDesign       = New(300002, "Purchase order is invalid to reject design", http.StatusUnprocessableEntity)
	ErrPoInvalidToUploadDesign       = New(300003, "Purchase order is invalid to upload design", http.StatusUnprocessableEntity)
	ErrPoInvalidToUpdateRawMaterial  = New(300004, "Purchase order is invalid to update raw material", http.StatusUnprocessableEntity)
	ErrPoInvalidToMarkMaking         = New(300005, "Purchase order is invalid to mark making", http.StatusUnprocessableEntity)
	ErrPoInvalidToMarkSubmit         = New(300006, "Purchase order is invalid to mark submit", http.StatusUnprocessableEntity)
	ErrPoInvalidToMarkDelivering     = New(300007, "Purchase order is invalid to mark delivering", http.StatusUnprocessableEntity)
	ErrPoInvalidToConfirmDelivered   = New(300008, "Purchase order is invalid to confirm delivered", http.StatusUnprocessableEntity)
	ErrPoIsAlreadyPaid               = New(300009, "Purchase order is already paid", http.StatusUnprocessableEntity)
	ErrPoInvalidToApproveRawMaterial = New(300010, "Order is not ready to approve raw material", http.StatusUnprocessableEntity)
	ErrPoInvalidToSkipMaterial       = New(300011, "Purchase order is invalid to skip raw material", http.StatusUnprocessableEntity)
	ErrPOInvoiceAlreadyGenerated     = New(300012, "Purchase order invoice is already generated", http.StatusUnprocessableEntity)
	ErrPOInvalidToSendRawMaterial    = New(300013, "Purchase order is invalid to send material", http.StatusUnprocessableEntity)
	ErrPONotFound                    = New(300014, "Purchase order is not found", http.StatusUnprocessableEntity)
	ErrPONInvalid                    = New(300015, "Purchase orders are invalid", http.StatusUnprocessableEntity)
	ErrPOIsNotAbleToCancel           = New(300016, "Purchase order is not able to cancel", http.StatusUnprocessableEntity)
	ErrPOClientReferenceIDDuplicated = New(300017, "Purchase order client reference id is duplidated", http.StatusUnprocessableEntity)
	ErrPoIsAlreadyConfirmed          = New(300018, "Purchase order is already confirmed", http.StatusUnprocessableEntity)
	ErrPOIsNotAbleToUploadPO         = New(300019, "Purchase order is not able to upload new PO", http.StatusUnprocessableEntity)
	ErrPORefIDDuplicate              = New(300020, "Purchase order reference id is duplicate", http.StatusBadRequest)
)

var (
	ErrBulkPoInvalidToSubmitQuotation           = New(400000, "Order is not ready to send quotation", http.StatusUnprocessableEntity)
	ErrBulkPoInvalidToApproveRawMaterial        = New(400001, "Order is not ready to approve raw material", http.StatusUnprocessableEntity)
	ErrBulkPoInvalidToCheckout                  = New(400002, "Order is not ready to checkout", http.StatusUnprocessableEntity)
	ErrBulkPoInvalidToChangeTrackingStatus      = New(400003, "Order is not ready to change tracking status", http.StatusUnprocessableEntity)
	ErrBulkPoInvoiceAlreadyGenerated            = New(400004, "Bulk PO invoice is already generated", http.StatusUnprocessableEntity)
	ErrBulkPoFirstPaymentAlreaydPaid            = New(400005, "Bulk PO first payment is already paid", http.StatusUnprocessableEntity)
	ErrBulkPoDepositAlreaydPaid                 = New(400006, "Bulk PO deposit amount is already paid", http.StatusUnprocessableEntity)
	ErrBulkPoDepositTransactionReferenceInvalid = New(400007, "Bulk PO deposit transaction reference is invalid", http.StatusUnprocessableEntity)
	ErrBulkPoDepositAmountInvalid               = New(400008, "Bulk PO deposit amount is invalid", http.StatusUnprocessableEntity)
	ErrBulkPoSecondPaymentAlreaydPaid           = New(400009, "Bulk PO second payment is already paid", http.StatusUnprocessableEntity)
	ErrBulkPoFinalPaymentAlreaydPaid            = New(400010, "Bulk PO final payment is already paid", http.StatusUnprocessableEntity)
	ErrBulkPoInvalidToCreatePaymentLink         = New(400011, "Bulk Order is invalid to create payment link", http.StatusUnprocessableEntity)
	ErrBulkPoNotFound                           = New(400012, "Bulk Order is not found", http.StatusUnprocessableEntity)
	ErrBulkQuotationIsAlreadyApproved           = New(400013, "Bulk quotation is already approved", http.StatusUnprocessableEntity)
	ErrBulkPoInvalidToSendQuotationToBuyer      = New(200009, "Bulk is invalid to send quotation to buyer", http.StatusUnprocessableEntity)
	ErrBulkPoNotAbleToStart                     = New(400014, "Bulk order is not able to start", http.StatusUnprocessableEntity)
	ErrBulkPoNotAbleToConfirm                   = New(400015, "Bulk order is not able to confirm", http.StatusUnprocessableEntity)
	ErrBulkPoNotAbleToUpdatePO                  = New(400016, "Bulk order is not able to update PO", http.StatusUnprocessableEntity)
	ErrBulkQuotationEmpty                       = New(400017, "Bulk quotation is required", http.StatusUnprocessableEntity)
)

var (
	ErrPaymentTransactionAlreadyPaid             = New(500000, "The transaction is already paid", http.StatusUnprocessableEntity)
	ErrPaymentTransactionIsInvalid               = New(500001, "The transaction is invalid", http.StatusUnprocessableEntity)
	ErrPaymentTransactionInvoiceAlreadyGenerated = New(500002, "The transaction's invoice is already generated", http.StatusUnprocessableEntity)
	ErrPaymentTransactionNotFound                = New(500002, "The transaction is not found", http.StatusUnprocessableEntity)
	ErrPaymentTransactionNotPaid                 = New(500003, "The transaction is not paid", http.StatusUnprocessableEntity)
)

var (
	ErrOrderGroupNotFound     = New(600000, "Order group not found", http.StatusNotFound)
	ErrOrderGroupUserIDEmpty  = New(600001, "Orders group user_id is required", http.StatusBadRequest)
	ErrOrderItemNotFound      = New(600002, "Order item not found", http.StatusNotFound)
	ErrOrderInvalid           = New(600003, "Order is invalid", http.StatusBadRequest)
	ErrOrderItemInvalid       = New(600004, "Order item is invalid", http.StatusBadRequest)
	ErrOrderItemIsAlreadyPaid = New(600005, "Order item is already paid", http.StatusUnprocessableEntity)
	ErrOrderEmpty             = New(600006, "Order is empty", http.StatusBadRequest)
	ErrOrderCurrencyMismatch  = New(600007, "Orders currency are mismatch", http.StatusBadRequest)
)

var (
	ErrBulkPurchaseOrderSellerQuotationNotFound         = New(700000, "Quotation is not found", http.StatusNotFound)
	ErrBulkPurchaseOrderSellerQuotationInvalidToApprove = New(700001, "Quotation is invalid to approve", http.StatusUnprocessableEntity)
	ErrBulkPurchaseOrderSellerQuotationInvalidToReject  = New(700002, "Quotation is invalid to reject", http.StatusUnprocessableEntity)
	ErrBulkPurchaseOrderSellerQuotationInvalidToSubmit  = New(700003, "Quotation is invalid to submit", http.StatusNotFound)
)

var (
	ErrDocumentNotFound         = New(800000, "Document not found")
	ErrDocumentCateNotFound     = New(800001, "Document category not found")
	ErrDocumentTagNotFound      = New(800002, "Document tag not found")
	ErrDocumentTagExisted       = New(800002, "Document tag name is already existed")
	ErrDocumentVisibleToInvalid = New(800003, "Document invisible to is invalid")
)

var (
	ErrInvoiceGeneratePdfError = New(900001, "Generate invoice's pdf failed", http.StatusUnprocessableEntity)
)
